#!/bin/bash
if [ "$1" == "" ]
then
echo "usage: editcmd [command]"
echo "edit any command in your PATH"
echo "example: editcmd lscmd"
exit 0
fi

if ! `lscmd $1`
then
echo "editcmd: error: couldn't find command ${1}"
exit 1
fi

declare cmddir=`cmddir $1`

sudo nano "$cmddir/$1"