#!/bin/bash

if [ "$1" == "" ] || [ ! "$num" -eq "$num" ] 2>/dev/null
then
echo "usage: findcmd [search string] [amount]"
echo "list commands from PATH directories based on a search string"
echo "examples:"
echo "findcmd find 5"
echo "findcmd ls"
exit 0
fi

declare results=`find $(path) | grep "$1"`
if [ "$2" != "" ]
then
if [ "$2" > 0 ]
then
results=`echo $results | head -n "$2"`
fi
fi
declare len=0
for i in $results; do (( len += 1 )); done
if [ $len == 0 ]
then
echo "findcmd: found no results"
exit 1
fi
echo "findcmd: found $len results:"
for i in $results; do echo `basename $i`; done