#!/bin/bash

if [ "$1" == "" ]
then
echo "usage: lscmd [command]"
echo "check if a command in your PATH exists"
echo "example: lscmd find"
echo "exit codes:"
echo "0: command exists"
echo "1: command doesn't exist"
exit 0
fi

cmddir &>/dev/null
exit $?