#!/bin/bash
if [ "$1" == "" ]
then
echo "usage: rmcmd [command]"
echo "delete any command from your PATH"
echo "example: rmcmd lscmd"
exit 0
fi

if ! `lscmd $1`
then
echo "rmcmd: error: couldn't find command ${1}"
exit 1
fi

declare cmddir=`cmddir $1`

sudo rm $cmddir/$1 && echo "rmcmd: successfully deleted command $1"
